### ISSUE TITLE
Practica_5_de_modelo_de_bizagi

### ISSUE THREAD

**Issue by JeroRoque** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-equipo-evelin#1]
[Practica 5-Fundamento _Dropshipping.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-equipo-evelin/files/12836810/Practica.5-Fundamento._Dropshipping.pdf)

**Comment by isaireyesp1** [comment]
Portada : 25
Procedimiento : 22
Figuras, ilustraciones y fotografías. : 25
Resultados y conclusiones : 22
calificación : 18.8

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
